name: Tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
      - name: Start backing services
        run: docker compose up -d
#      - name: Wait for services to come up (NOTE: building the binary should take long enough)
#        run: sleep 5
      - name: Install build dependencies
        run: make install
      - name: Build binary
        run: make build
      - name: Migrate database
        run: make db-migrate
      - name: Create s3 bucket
        run: make create-s3-bucket
      - name: Run vet, lint, tests
        run: make check
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
